language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
  - "8"
script:
  - npm run lint
  - npm run cover

after_script:
  - npm run publish-coverage

cache:
  directories:
      - node_modules
